# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68f0679f7a9df94457d576a83978ae4acbc3d83bd5b35c32d2d7f5b39f381ca51ccb01dc0cc4128508f716363b003b56c55d0893c0788aeb475bf19486c0ef0e

test:
  secret_key_base: 43e4f3b0df1bf4104be9ec137445666696357758556f7ae2961c88606c21480ea87ce3fa939f5bf3e66011d956c1c69c68089d7b27d8135b3276bb299878e5b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
